version: "3.8"

services:
  web:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    command: sh -c "sleep 5 && streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0"

  db:
    image: postgres:13
    ports:
      - "2123:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s #increased interval
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
